name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # BƯỚC MỚI: Chuyển đổi tên repository thành chữ thường
    - name: Convert repository name to lowercase
      id: string-actions
      run: echo "repo_lowercase=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push ARM64 image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm64
        push: true
        # SỬA LỖI Ở ĐÂY: Dùng biến chữ thường đã được tạo ở bước trên
        tags: ghcr.io/${{ steps.string-actions.outputs.repo_lowercase }}:latest
